import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const testDir = dirname(fileURLToPath(import.meta.url));
const appRoot = join(testDir, "..");

function readAppFile(path) {
  return readFileSync(join(appRoot, path), "utf8");
}

test("agent preflight client has a blocked fallback instead of throwing into the dashboard", () => {
  const apiSource = readAppFile("lib/api.ts");

  assert.match(apiSource, /export async function getAgentPreflightSafe/);
  assert.match(apiSource, /catch \(error\)/);
  assert.match(apiSource, /status: "blocked"/);
  assert.match(apiSource, /Agent Ops preflight could not be loaded/);
});

test("dashboard uses safe preflight loading and keeps paper-order visibility", () => {
  const pageSource = readAppFile("app/page.tsx");
  const apiSource = readAppFile("lib/api.ts");
  const dataHealthSource = readAppFile("app/components/data-health-panel.tsx");
  const importBlock = pageSource.slice(
    pageSource.indexOf("import {"),
    pageSource.indexOf("} from \"@/lib/api\";") + 1
  );

  assert.match(apiSource, /NEXT_PUBLIC_API_BASE_URL\?\.trim\(\) \|\| "http:\/\/localhost:8000"/);
  assert.match(importBlock, /getAgentPreflightSafe/);
  assert.match(importBlock, /getLiveDashboard/);
  assert.doesNotMatch(importBlock, /getAgentPreflight,/);
  assert.doesNotMatch(importBlock, /getIngestionRuns/);
  assert.doesNotMatch(importBlock, /getDailyCostReport/);
  assert.doesNotMatch(importBlock, /getDailyMetrics/);
  assert.doesNotMatch(importBlock, /getLiveSignals/);
  assert.doesNotMatch(importBlock, /getOperationalState/);
  assert.doesNotMatch(importBlock, /getTodayMatches/);
  assert.match(pageSource, /getAgentPreflightSafe\(\)/);
  assert.match(pageSource, /getLiveDashboard\(\)/);
  assert.match(pageSource, /const auxiliaryResultsPromise = Promise\.allSettled/);
  assert.match(pageSource, /const nextDashboard = await getLiveDashboard\(\)/);
  assert.match(pageSource, /setLoading\(false\);[\s\S]*void auxiliaryResultsPromise\.then/);
  assert.match(pageSource, /Estado operacional carregado; painel auxiliar indisponivel/);
  assert.match(pageSource, /Estado operacional indisponivel/);
  assert.match(pageSource, /nextDashboard\.operational_state/);
  assert.match(pageSource, /nextDashboard\.matches/);
  assert.match(pageSource, /nextDashboard\.metrics/);
  assert.match(pageSource, /nextDashboard\.signals/);
  assert.match(pageSource, /nextDashboard\.readiness/);
  assert.match(pageSource, /replayOddsScenario/);
  assert.match(pageSource, /setReplayOddsScenario/);
  assert.match(pageSource, /runReplay\(selectedMatchId, adminToken\.trim\(\), replayOddsScenario\)/);
  assert.match(importBlock, /runReplayContracts/);
  assert.match(importBlock, /runDailyOperationalLoop/);
  assert.match(pageSource, /triggerReplayContracts/);
  assert.match(pageSource, /triggerDailyOperationalRun/);
  assert.match(pageSource, /runReplayContracts\(selectedMatchId \?\? "match_atp_002", token\)/);
  assert.match(pageSource, /runDailyOperationalLoop\(token, selectedMatchId \?\? "match_atp_002", 100\)/);
  assert.match(pageSource, /onRunReplayContracts=\{triggerReplayContracts\}/);
  assert.match(pageSource, /onRunDailyOperational=\{triggerDailyOperationalRun\}/);
  assert.match(pageSource, /dailyOperationalRun=\{dailyOperationalRun\}/);
  assert.match(pageSource, /dailyOpsBusy=\{dailyOpsBusy\}/);
  assert.match(pageSource, /replayContract\.scenarios/);
  assert.match(apiSource, /use_fixture_seed: true/);
  assert.match(apiSource, /export async function runReplayContracts/);
  assert.match(apiSource, /\/api\/v1\/replay\/contracts\/run/);
  assert.match(apiSource, /export async function runDailyOperationalLoop/);
  assert.match(apiSource, /\/api\/v1\/ops\/daily/);
  assert.match(pageSource, /nextOperational\.daily_cost_report/);
  assert.match(pageSource, /nextOperational\.api_onboarding/);
  assert.match(pageSource, /nextOperational\.model_lab/);
  assert.match(pageSource, /nextOperational\.replay_lab/);
  assert.match(pageSource, /nextOperational\.provider_mode_matrix/);
  assert.match(pageSource, /budget_replay_fixtures/);
  assert.match(pageSource, /Live readiness/);
  assert.match(pageSource, /can_generate_entries/);
  assert.match(pageSource, /apiOnboarding=\{apiOnboarding\}/);
  assert.match(pageSource, /ingestionRuns=\{ingestionRuns\}/);
  assert.match(pageSource, /providerModeMatrix=\{providerModeMatrix\}/);
  assert.match(pageSource, /providerModeReason=\{providerModeReason\}/);
  assert.match(pageSource, /sourceSummary=\{sourceSummary\}/);
  assert.match(pageSource, /readiness=\{readiness\}/);
  assert.match(pageSource, /replayLab=\{replayLab\}/);
  assert.match(apiSource, /\/api\/v1\/dashboard\/live-state/);
  assert.match(apiSource, /odds_scenario: oddsScenario/);
  assert.match(dataHealthSource, /Ingestion Journal/);
  assert.match(dataHealthSource, /API Onboarding/);
  assert.match(dataHealthSource, /Core primeiro, providers por etapas/);
  assert.match(dataHealthSource, /Replay Contracts/);
  assert.match(dataHealthSource, /Daily Ops/);
  assert.match(dataHealthSource, /latestDailyOpsRun/);
  assert.match(dataHealthSource, /run\.run_type === "daily_operational_run"/);
  assert.match(dataHealthSource, /persisted \$/);
  assert.match(dataHealthSource, /live calls/);
  assert.match(dataHealthSource, /model_lab_backtest/);
  assert.match(dataHealthSource, /onRunDailyOperational/);
  assert.match(dataHealthSource, /onRunReplayContracts/);
  assert.match(dataHealthSource, /replayContractBusy/);
  assert.match(dataHealthSource, /Run replay contract scenarios/);
  assert.match(dataHealthSource, /Provider Mode Matrix/);
  assert.match(dataHealthSource, /Operational Truth/);
  assert.match(dataHealthSource, /Modo, cursor e replay contract/);
  assert.match(dataHealthSource, /activeMode/);
  assert.match(dataHealthSource, /Source truth/);
  assert.match(dataHealthSource, /sourceSummary\.persisted_matches/);
  assert.match(dataHealthSource, /sourceSummary\.volatile_matches/);
  assert.match(dataHealthSource, /Readiness gate/);
  assert.match(dataHealthSource, /readiness\?\.can_generate_entries/);
  assert.match(dataHealthSource, /Cursor\/freshness blocks/);
  assert.match(dataHealthSource, /stale feeds/);
  assert.match(dataHealthSource, /contractStatusLabel/);
  assert.match(dataHealthSource, /ingestionRunSummary/);
  assert.match(dataHealthSource, /missing blocks Entrada/);
  assert.match(dataHealthSource, /providerModeMatrix\.map/);
  assert.match(dataHealthSource, /entries \{step\.entry_gate\}/);
  assert.match(dataHealthSource, /replayLab\.providers/);
  assert.match(dataHealthSource, /replayLab\.last_contract_persistence/);
  assert.match(dataHealthSource, /raw_payloads_saved/);
  assert.match(dataHealthSource, /provider_cursors_replayed/);
  assert.match(dataHealthSource, /provider_latency_saved/);
  assert.match(dataHealthSource, /provider_contracts/);
  assert.match(dataHealthSource, /settlement_decisions/);
  assert.match(dataHealthSource, /match_freshness/);
  assert.match(dataHealthSource, /apiOnboarding\.steps/);
  assert.match(dataHealthSource, /last smoke/);
  assert.match(dataHealthSource, /step\.last_smoke_status/);
  assert.match(dataHealthSource, /Ultimos ciclos persistidos/);
  assert.match(dataHealthSource, /run\.run_type === "replay_run"/);
  assert.match(dataHealthSource, /events_replayed/);
  assert.match(dataHealthSource, /resync required/);
  assert.match(dataHealthSource, /cursorStatusClass/);
  assert.match(dataHealthSource, /expected_next_seq/);
  assert.match(dataHealthSource, /resync_required/);
  assert.match(pageSource, /Training Dataset/);
  assert.match(pageSource, /modelLab\.source/);
  assert.match(pageSource, /modelLab\.training_examples/);
  assert.match(apiSource, /export async function autoSettlePaperOrders/);
  assert.match(pageSource, /triggerAutoPaperSettlement/);
  assert.match(pageSource, /autoSettlePaperOrders\(token, selectedMatchId \?\? undefined, 100\)/);
  assert.match(pageSource, /Auto-settle paper/);
  assert.match(pageSource, /autoSettlement\.evaluated_orders/);
  assert.match(pageSource, /autoSettlement\.decisions/);
  assert.match(pageSource, /\["Paper orders", String\(agentBriefing\?\.paper_orders \?\? 0\)\]/);
});
