from datetime import datetime, timedelta, timezone
from tennis_edge.domain import (
    CompetitionLevel,
    Match,
    MatchState,
    OddsQuote,
    Provider,
    RawProviderPayload,
    Player,
    Surface,
    Tour,
)
from tennis_edge.services.normalizer import payload_checksum


NOW = datetime.now(timezone.utc).replace(microsecond=0)


def _quote(bookmaker: str, player_id: str, odds: float, minutes_ago: int = 1) -> OddsQuote:
    return OddsQuote(
        bookmaker=bookmaker,
        player_id=player_id,
        decimal_odds=odds,
        source_ts=datetime.now(timezone.utc).replace(microsecond=0)
        - timedelta(seconds=minutes_ago),
    )


PLAYERS = {
    "atp_sinner": Player(
        id="atp_sinner",
        provider_ids={"betfair_selection_id": "1001"},
        name="Jannik Sinner",
        tour=Tour.ATP,
        country="ITA",
        ranking=1,
        elo_overall=2240,
        elo_clay=2145,
        elo_hard=2295,
        hold_rate=0.88,
        break_rate=0.34,
        recent_win_rate=0.93,
        fatigue_risk=0.22,
    ),
    "atp_musetti": Player(
        id="atp_musetti",
        provider_ids={"betfair_selection_id": "1002"},
        name="Lorenzo Musetti",
        tour=Tour.ATP,
        country="ITA",
        ranking=9,
        elo_overall=1915,
        elo_clay=2010,
        elo_hard=1815,
        hold_rate=0.80,
        break_rate=0.28,
        recent_win_rate=0.68,
        fatigue_risk=0.28,
    ),
    "atp_zverev": Player(
        id="atp_zverev",
        provider_ids={"betfair_selection_id": "1003"},
        name="Alexander Zverev",
        tour=Tour.ATP,
        country="GER",
        ranking=3,
        elo_overall=2045,
        elo_clay=1990,
        elo_hard=2050,
        hold_rate=0.86,
        break_rate=0.25,
        recent_win_rate=0.72,
        fatigue_risk=0.3,
    ),
    "atp_navone": Player(
        id="atp_navone",
        provider_ids={"betfair_selection_id": "1004"},
        name="Mariano Navone",
        tour=Tour.ATP,
        country="ARG",
        ranking=44,
        elo_overall=1760,
        elo_clay=1885,
        elo_hard=1650,
        hold_rate=0.75,
        break_rate=0.3,
        recent_win_rate=0.61,
        fatigue_risk=0.18,
    ),
    "wta_swiatek": Player(
        id="wta_swiatek",
        provider_ids={"betfair_selection_id": "2001"},
        name="Iga Swiatek",
        tour=Tour.WTA,
        country="POL",
        ranking=3,
        elo_overall=2145,
        elo_clay=2250,
        elo_hard=2040,
        hold_rate=0.79,
        break_rate=0.43,
        recent_win_rate=0.74,
        fatigue_risk=0.2,
    ),
    "wta_andreeva": Player(
        id="wta_andreeva",
        provider_ids={"betfair_selection_id": "2002"},
        name="Mirra Andreeva",
        tour=Tour.WTA,
        country="RUS",
        ranking=7,
        elo_overall=2005,
        elo_clay=2040,
        elo_hard=1965,
        hold_rate=0.74,
        break_rate=0.39,
        recent_win_rate=0.7,
        fatigue_risk=0.24,
    ),
    "wta_gauff": Player(
        id="wta_gauff",
        provider_ids={"betfair_selection_id": "2003"},
        name="Coco Gauff",
        tour=Tour.WTA,
        country="USA",
        ranking=4,
        elo_overall=2050,
        elo_clay=2010,
        elo_hard=2075,
        hold_rate=0.75,
        break_rate=0.41,
        recent_win_rate=0.67,
        fatigue_risk=0.27,
    ),
    "wta_keys": Player(
        id="wta_keys",
        provider_ids={"betfair_selection_id": "2004"},
        name="Madison Keys",
        tour=Tour.WTA,
        country="USA",
        ranking=11,
        elo_overall=1910,
        elo_clay=1850,
        elo_hard=1955,
        hold_rate=0.78,
        break_rate=0.31,
        recent_win_rate=0.58,
        fatigue_risk=0.23,
    ),
    "itf_lima": Player(
        id="itf_lima",
        provider_ids={"betfair_selection_id": "3001"},
        name="Mateo Lima",
        tour=Tour.ATP,
        country="BRA",
        ranking=612,
        elo_overall=1395,
        elo_clay=1440,
        elo_hard=1330,
        hold_rate=0.69,
        break_rate=0.23,
        recent_win_rate=0.55,
        fatigue_risk=0.34,
    ),
    "itf_sato": Player(
        id="itf_sato",
        provider_ids={"betfair_selection_id": "3002"},
        name="Ren Sato",
        tour=Tour.ATP,
        country="JPN",
        ranking=734,
        elo_overall=1350,
        elo_clay=1320,
        elo_hard=1390,
        hold_rate=0.67,
        break_rate=0.21,
        recent_win_rate=0.52,
        fatigue_risk=0.3,
    ),
}


def sample_matches() -> list[Match]:
    p = PLAYERS
    return [
        Match(
            id="match_atp_001",
            provider_ids={"betfair_market_id": "1.100000001"},
            provider_match_id="sample-api-tennis-001",
            tournament="Rome Masters",
            round="R16",
            tour=Tour.ATP,
            surface=Surface.CLAY,
            best_of=3,
            scheduled_at=NOW + timedelta(minutes=35),
            player1=p["atp_sinner"],
            player2=p["atp_musetti"],
            state=MatchState(status="prematch"),
            odds=[
                _quote("Pinnacle", "atp_sinner", 1.38),
                _quote("Pinnacle", "atp_musetti", 3.12),
                _quote("Bet365", "atp_sinner", 1.36),
                _quote("Bet365", "atp_musetti", 3.25),
                _quote("Betfair", "atp_sinner", 1.4),
                _quote("Betfair", "atp_musetti", 3.08),
            ],
        ),
        Match(
            id="match_atp_002",
            provider_ids={"betfair_market_id": "1.100000002"},
            provider_match_id="sample-api-tennis-002",
            tournament="Rome Masters",
            round="R16",
            tour=Tour.ATP,
            surface=Surface.CLAY,
            best_of=3,
            scheduled_at=NOW - timedelta(minutes=18),
            player1=p["atp_zverev"],
            player2=p["atp_navone"],
            state=MatchState(
                status="live",
                p1_sets=0,
                p2_sets=0,
                p1_games=4,
                p2_games=3,
                point_score="30-15",
                server_player_id="atp_zverev",
                momentum_player_id="atp_zverev",
                source_latency_ms=410,
            ),
            odds=[
                _quote("Pinnacle", "atp_zverev", 1.31),
                _quote("Pinnacle", "atp_navone", 3.65),
                _quote("Bet365", "atp_zverev", 1.29),
                _quote("Bet365", "atp_navone", 3.75),
                _quote("Betfair", "atp_zverev", 1.34),
                _quote("Betfair", "atp_navone", 3.58),
            ],
        ),
        Match(
            id="match_gs_001",
            provider_ids={"betfair_market_id": "1.100000005"},
            provider_match_id="sample-api-tennis-005",
            tournament="Roland Garros",
            round="R32",
            tour=Tour.ATP,
            competition_level=CompetitionLevel.ATP,
            surface=Surface.CLAY,
            best_of=5,
            scheduled_at=NOW + timedelta(hours=4),
            player1=p["atp_sinner"],
            player2=p["atp_zverev"],
            state=MatchState(status="prematch"),
            odds=[
                _quote("Pinnacle", "atp_sinner", 1.58),
                _quote("Pinnacle", "atp_zverev", 2.48),
                _quote("Bet365", "atp_sinner", 1.55),
                _quote("Bet365", "atp_zverev", 2.55),
                _quote("Betfair", "atp_sinner", 1.6),
                _quote("Betfair", "atp_zverev", 2.44),
            ],
        ),
        Match(
            id="match_wta_001",
            provider_ids={"betfair_market_id": "1.100000003"},
            provider_match_id="sample-api-tennis-003",
            tournament="Rome WTA",
            round="QF",
            tour=Tour.WTA,
            surface=Surface.CLAY,
            best_of=3,
            scheduled_at=NOW - timedelta(minutes=56),
            player1=p["wta_swiatek"],
            player2=p["wta_andreeva"],
            state=MatchState(
                status="live",
                p1_sets=1,
                p2_sets=0,
                p1_games=2,
                p2_games=3,
                point_score="40-40",
                server_player_id="wta_andreeva",
                is_break_point=True,
                momentum_player_id="wta_andreeva",
                source_latency_ms=520,
            ),
            odds=[
                _quote("Pinnacle", "wta_swiatek", 1.64),
                _quote("Pinnacle", "wta_andreeva", 2.36),
                _quote("Bet365", "wta_swiatek", 1.61),
                _quote("Bet365", "wta_andreeva", 2.42),
                _quote("Betfair", "wta_swiatek", 1.67),
                _quote("Betfair", "wta_andreeva", 2.3),
            ],
        ),
        Match(
            id="match_wta_002",
            provider_ids={"betfair_market_id": "1.100000004"},
            provider_match_id="sample-api-tennis-004",
            tournament="Rome WTA",
            round="R16",
            tour=Tour.WTA,
            surface=Surface.CLAY,
            best_of=3,
            scheduled_at=NOW + timedelta(hours=2),
            player1=p["wta_gauff"],
            player2=p["wta_keys"],
            state=MatchState(status="prematch"),
            odds=[
                _quote("Pinnacle", "wta_gauff", 1.71),
                _quote("Pinnacle", "wta_keys", 2.2),
                _quote("Bet365", "wta_gauff", 1.68),
                _quote("Bet365", "wta_keys", 2.25),
                _quote("Betfair", "wta_gauff", 1.73),
                _quote("Betfair", "wta_keys", 2.18),
            ],
        ),
        Match(
            id="match_itf_001",
            provider_ids={
                "sportradar": "sr:match:itf-001",
                "txodds": "TX-ITF-001",
                "betfair_market_id": "1.100000006",
            },
            provider_match_id="sample-itf-001",
            tournament="ITF M25 Curitiba",
            round="R32",
            tour=Tour.ATP,
            competition_level=CompetitionLevel.ITF,
            surface=Surface.CLAY,
            best_of=3,
            scheduled_at=NOW - timedelta(minutes=8),
            player1=p["itf_lima"],
            player2=p["itf_sato"],
            state=MatchState(
                status="live",
                p1_sets=0,
                p2_sets=0,
                p1_games=1,
                p2_games=2,
                point_score="15-30",
                server_player_id="itf_lima",
                momentum_player_id="itf_sato",
                source_latency_ms=1450,
            ),
            odds=[
                _quote("LowLimitBook", "itf_lima", 1.86, minutes_ago=2),
                _quote("LowLimitBook", "itf_sato", 1.98, minutes_ago=2),
            ],
        ),
    ]


def _payload(
    provider: Provider,
    payload_type: str,
    source_event_id: str,
    payload: dict,
    seconds_ago: int,
) -> RawProviderPayload:
    source_ts = NOW - timedelta(seconds=seconds_ago)
    checksum = payload_checksum(provider, payload_type, payload, source_event_id, source_ts)
    return RawProviderPayload(
        id=f"{provider}:{payload_type}:{source_event_id}:{checksum[:12]}",
        provider=provider,
        payload_type=payload_type,  # type: ignore[arg-type]
        source_event_id=source_event_id,
        source_ts=source_ts,
        payload=payload,
        checksum=checksum,
    )


def sample_raw_payloads(match_id: str = "match_atp_002") -> list[RawProviderPayload]:
    return [
        _payload(
            Provider.SPORTRADAR,
            "score",
            match_id,
            {
                "sport_event_id": "sr:match:atp-002",
                "match_id": match_id,
                "status": "live",
                "home_score": {"sets": 0, "games": 3, "point": "40"},
                "away_score": {"sets": 0, "games": 3, "point": "30"},
                "server": "atp_zverev",
                "period": "FIRST_SET",
                "last_point_result": "serve_winner",
            },
            95,
        ),
        _payload(
            Provider.TXODDS,
            "odds",
            match_id,
            {
                "match_id": match_id,
                "bookmaker": "Pinnacle",
                "market": "ML",
                "odds": {
                    "atp_zverev": 1.42,
                    "atp_navone": 3.05,
                },
            },
            92,
        ),
        _payload(
            Provider.BETRADAR_UOF,
            "market_state",
            match_id,
            {
                "match_id": match_id,
                "bookmaker": "BetradarLive",
                "market": "ML",
                "status": "suspended",
                "reason": "betstop during break point review",
            },
            74,
        ),
        _payload(
            Provider.SPORTRADAR,
            "point",
            match_id,
            {
                "match_id": match_id,
                "sequence": 88,
                "set_number": 1,
                "game_number": 8,
                "server": "atp_zverev",
                "winner": "atp_navone",
                "point_score": "40-40",
                "description": "Navone wins return point to deuce",
            },
            70,
        ),
        _payload(
            Provider.SPORTRADAR,
            "score",
            match_id,
            {
                "sport_event_id": "sr:match:atp-002",
                "match_id": match_id,
                "status": "live",
                "home_score": {"sets": 0, "games": 4, "point": "30"},
                "away_score": {"sets": 0, "games": 3, "point": "15"},
                "server": "atp_zverev",
                "period": "FIRST_SET",
                "last_point_result": "forehand_winner",
            },
            55,
        ),
        _payload(
            Provider.TXODDS,
            "odds",
            match_id,
            {
                "match_id": match_id,
                "bookmaker": "Pinnacle",
                "market": "ML",
                "odds": {
                    "atp_zverev": 1.31,
                    "atp_navone": 3.65,
                },
            },
            50,
        ),
    ]
